name: Zip file Demo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create integration folder
    steps:
    - uses: actions/checkout@master
    - run: cd src/css && tar cf integration.tar style.scss
    - run: mv src/css/integration.tar src/js
    - run: cd src/js && tar rf integration.tar script.js
    - run: cd src/js && gzip --force integration.tar -9
    - run: ls src/js
     
        
    
  
