name: Bash Demo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create integration folder
      run: | 
        sh 'cd src/css && tar cf integration.tar style.scss'
        sh 'mv src/css/integration.tar src/js'
