name: Bash Demo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Basg file execution demo
      run: |
        mkdir -p myNewFolder/myNewSubFolder
