name: Bash Demo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create integration folder
      run: | 
        mkdir -p ./integration
        cp src/css/ ./integration
