name: Bash Demo
on:
  schedule:
    - cron: '05 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Basg file execution demo
      run: bash scripts/pipeline/release.sh
