name: Upload zip using CLI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload file using CLI
    steps:
    - uses: actions/checkout@master
    - run: cd src/css && tar cf unit.tar style.scss
    - run: mv src/css/unit.tar src/js
    - run: cd src/js && find . "*.js" | xargs tar rf unit.tar
    - run: cd src/js && gzip --force unit.tar -9
    - run: ls src/js
    - run: pip install --quiet --no-cache-dir awscli
    - run: mkdir -p ~/.aws
    - run: touch ~/.aws/credentials
       aws_access_key_id = 'AKIAXGKI2BMQ3RTCF2MJ'
       aws_secret_access_key = ''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'' ~/.aws/credentials
       aws s3 cp ./src/js/unit.tar.gz s3://test-bucket-demo-vi-dk/unit.tar.gz
    - run: rm -rf ~/.aws

