name: Execute shell file
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Execute shell file
    steps:
    - uses: actions/checkout@master
    - run: chmod +x ./sh_file.sh
    - shell : bash
