name: Execute shell file
on:
  push:
    branches: [ master ]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file demo
      run: bash upload_to_s3.sh ./src/index.html ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_S3_BUCKET}} ${{secrets.S3_KEY}}

