name: Zip Tar file Demo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Unit folder
    steps:
    - uses: actions/checkout@master
    - run: cd src/css && tar cf unit.tar style.scss
    - run: mv src/css/unit.tar src/js
    - run: cd src/js && find . "*.js" | xargs tar rf unit.tar
    - run: cd src/js && gzip --force unit.tar -9
    - run: ls src/js
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl BucketOwnerFullControl
      env:
        FILE: ./src/js/unit.tar.gz
        AWS_REGION: 'ap-south-1'
        S3_BUCKET: 'test-bucket-demo-vi-dk'
        S3_KEY: 'arn:aws:s3:::test-bucket-demo-vi-dk'
        AWS_ACCESS_KEY_ID: 'AKIAXGKI2BMQ3RTCF2MJ'
        AWS_SECRET_ACCESS_KEY: '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'
