name: Upload zip using marketplace
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Unit folder
    steps:
    - uses: actions/checkout@master
    - run: cd src/css && tar cf unit.tar style.scss
    - run: mv src/css/unit.tar src/js
    - run: cd src/js && find . "*.js" | xargs tar rf unit.tar
    - run: cd src/js && gzip --force unit.tar -9
    - run: ls src/js
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl bucket-owner-full-control
      env:
        FILE: ./src/js/unit.tar.gz
        AWS_REGION: 'ap-south-1'
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}/fol2/test-results-2
        S3_KEY: ${{ secrets.S3_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
